server:
  port: 28080

spring:
  application:
    name: play-films-v1
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/play_films
    username: postgres
    password: admin

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

logging:
  pattern:
    level: "%5p [${spring.application.name:}%X{traceId:-}%X{spanId:-}]"
  level:
    io:
      micrometer:
        tracing: debug

springdoc:
  swagger-ui:
    path: /play-films-v0.0.1.yml

tmdb:
  api-key: 91d7c89d616a91ba66ad259365f0f458
