openapi: 3.0.3
info:
  title: Play Films API
  version: 1.0.0
  description: API для онлайн-кинотеатра Play Films

servers:
  - url: http://localhost:8080/api/v1
    description: Локальный сервер разработки

paths:
  /movies:
    $ref: './paths/movies.yml#/movies'
  /movies/import-from-tmdb:
    $ref: './paths/movies.yml#/movies-import-from-tmdb'
  /users:
    $ref: './paths/users.yml#/users'
  /rating:
    $ref: './paths/rating.yml#/rating'
  /videoSource:
    $ref: './paths/videoSource.yml#/videoSource'
