package ru.shainedoc.desktop.playfilms.models.enums;

public enum Genre {
    ACTION("Боевик"),
    ADVENTURE("Приключения"),
    COMEDY("Комедия"),
    DRAMA("Драма"),
    FANTASY("Фэнтези"),
    SCIENCE_FICTION("Научная фантастика"),
    HORROR("Ужасы"),
    THRILLER("Триллер"),
    MYSTERY("Детектив"),
    ROMANCE("Романтика"),
    ANIMATION("Анимация"),
    DOCUMENTARY("Документальный"),
    HISTORICAL("Исторический"),
    CRIME("Криминал"),
    WESTERN("Вестерн"),
    WAR("Военный"),
    MUSICAL("Мюзикл"),
    FAMILY("Семейный"),
    BIOGRAPHY("Биография"),
    SPORT("Спортивный"),
    FANTASY_ADVENTURE("Фэнтезийные приключения"),
    SCIENCE_FICTION_ADVENTURE("Научно-фантастические приключения"),
    PSYCHOLOGICAL_THRILLER("Психологический триллер"),
    POLITICAL_THRILLER("Политический триллер"),
    LEGAL_THRILLER("Юридический триллер"),
    SPY("Шпионский"),
    SUPERHERO("Супергеройский"),
    FANTASY_COMEDY("Фэнтезийная комедия"),
    ROMANTIC_COMEDY("Романтическая комедия"),
    DARK_COMEDY("Чёрная комедия"),
    SATIRE("Сатира"),
    SLAPSTICK("Слэпстик"),
    EPIC("Эпический"),
    HISTORICAL_DRAMA("Историческая драма"),
    PERIOD_DRAMA("Костюмированная драма"),
    NEO_NOIR("Нео-нуар"),
    GANGSTER("Гангстерский"),
    HEIST("Ограбление"),
    DISASTER("Катастрофа"),
    POST_APOCALYPTIC("Постапокалиптический"),
    DYSTOPIAN("Антиутопия"),
    CYBERPUNK("Киберпанк"),
    STEAMPUNK("Стимпанк"),
    BIOPIC("Биографический"),
    MOCKUMENTARY("Псевдодокументальный"),
    FOUND_FOOTAGE("Псевдодокументальная съёмка"),
    SLASHER("Слэшер"),
    SUPERNATURAL("Сверхъестественное"),
    GOTHIC("Готический"),
    PARODY("Пародия"),
    SURREAL("Сюрреализм"),
    EXPERIMENTAL("Экспериментальный"),
    ROAD_MOVIE("Дорожное кино"),
    COMING_OF_AGE("Фильм о взрослении"),
    TEEN("Подростковый"),
    KIDS("Детский"),
    ANTHOLOGY("Антология"),
    SHORT_FILM("Короткометражный"),
    SILENT("Немой"),
    NOIR("Нуар"),
    MELODRAMA("Мелодрама"),
    TRAGEDY("Трагедия"),
    EROTIC("Эротический"),
    ROMANTIC_DRAMA("Романтическая драма"),
    ACTION_COMEDY("Боевик-комедия"),
    SCIENCE_FICTION_HORROR("Научно-фантастический хоррор"),
    HORROR_COMEDY("Комедийный хоррор"),
    FANTASY_DRAMA("Фэнтезийная драма"),
    WAR_DRAMA("Военная драма"),
    CRIME_DRAMA("Криминальная драма"),
    MEDICAL_DRAMA("Медицинская драма"),
    LEGAL_DRAMA("Юридическая драма"),
    POLITICAL_DRAMA("Политическая драма"),
    ADVENTURE_COMEDY("Приключенческая комедия"),
    SWASHBUCKLER("Пиратский/авантюрный"),
    MARTIAL_ARTS("Боевые искусства"),
    SAMURAI("Самурайский"),
    WUXIA("Уся"),
    MONSTER("Фильм о монстрах"),
    ZOMBIE("Зомби"),
    VAMPIRE("Вампирский"),
    WEREWOLF("Оборотни"),
    GHOST("Фильмы о призраках"),
    ALIEN("Фильмы о пришельцах"),
    TIME_TRAVEL("Путешествия во времени"),
    APOCALYPTIC("Апокалиптический"),
    SPACE_OPERA("Космическая опера"),
    ANTI_WAR("Антивоенный"),
    PSYCHOLOGICAL("Психологический"),
    ABSURDIST("Абсурдистский"),
    AVANT_GARDE("Авангардный"),
    CULT("Культовый"),
    B_MOVIE("Фильм категории B"),
    ART_HOUSE("Артхаус");

    private final String russianName;

    Genre(String russianName) {
        this.russianName = russianName;
    }

    @Override
    public String toString() {
        return String.valueOf(russianName);
    }
}
